POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZzdXR0ZXIiLCJpZCI6IjY3NTRiNGI5MzA5ZjMyZGRmMzQ5NjE1MyIsImlhdCI6MTczMzY4OTQ5OSwiZXhwIjoxNzMzNjkzMDk5fQ.PjcCyeAntdxpjQ2Ib_ztRqoFd7jHGe0VaBDDBbpV8fz

{
	"title": "Vanessas Blog",
	"author": "Vanessa Sutter",
    "url": "https://www.test.ch",
    "likes": 0
}